New file added
jayeshsony/Oops-Concepts pull request #1
Opened 2024-04-22 13:51 UTC by jayeshsony

Implemented the Oops concepts 13 to 16 Practicals.

2024-04-22 16:27 UTC, KrushaliTalaviya reviewed
Above the Class only one documentation comment or anytime Need to add only one documentation comment All thing you can add in that. You also can you
Tag for the new line and another some html tag also

Apply in all the files

2024-04-22 16:27 UTC, KrushaliTalaviya commented on EmployeeInfo.java
> +/**
Above the Class only one documentation comment or anytime Need to add only one documentation comment All thing you can add in that. You also can you <br> Tag for the new line and another some html tag also

2024-04-22 16:27 UTC, KrushaliTalaviya commented on ShapeAreaCalculator.java
> +/**
Above the Class only one documentation comment or anytime Need to add only one documentation comment All thing you can add in that. You also can you
Tag for the new line and another some html tag also

2024-04-22 16:27 UTC, KrushaliTalaviya commented on ShapeDrawer.java
> +// Abstract class representing different shapes.
Above the Class only one documentation comment or anytime Need to add only one documentation comment All thing you can add in that. You also can you
Tag for the new line and another some html tag also

2024-04-22 16:27 UTC, KrushaliTalaviya commented on StudentMarkSheet.java
> + *
Above the Class only one documentation comment or anytime Need to add only one documentation comment All thing you can add in that. You also can you
Tag for the new line and another some html tag also

2024-04-22 16:27 UTC, KrushaliTalaviya commented on ShapeDrawer.java
> +	@Override
We cann't user documentation comment for overriide method

2024-04-23 06:00 UTC, jayeshsony commented
Modified the practical 13, 14, 15 and 16th.

2024-04-23 13:37 UTC, jayeshsony commented
Created practical 17 to 25.

2024-04-23 17:02 UTC, KrushaliTalaviya requested changes

2024-04-23 17:02 UTC, KrushaliTalaviya commented on VehicleFunctionality.java
> +class Car extends Vehicle {
Add Space after starting comment like after this  //

2024-04-23 17:02 UTC, KrushaliTalaviya commented on ReadTestFile.java
> +			fileReader = new FileReader("myTestFile.txt");
You can give comment here after complete the try like like this 

fileReader = new FileReader("myTestFile.txt"); // Create FileReader instance

Apply this in the all the practical which you have used try catch and finally. Applyy in this three block.

2024-04-24 05:01 UTC, jayeshsony commented
Created PR changes in practical 15, 17,18, 24, 25.

2024-04-24 05:12 UTC, jayeshsony commented
Created PR changes in practical 15, 17, 18, 24 and 25.

2024-04-24 05:23 UTC, KrushaliTalaviya approved these changes

2024-04-24 05:23 UTC, merged